default: &default
  adapter: postgresql
  encoding: unicode

  username: gabriel
  password: 600425

  database: devise_example

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
